/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package serialisasi;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

/**
 *
 * @author LENOVO
 */
public class Settings extends javax.swing.JFrame {
    private LanguageSettings settings;
    private final String settingsFile = "languageSettings.ser";
    /**
     * Creates new form Settings
     */
    
    public Settings() {
        initComponents();
        cmbBhs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Indonesia" }));
        loadSettings(); // Memuat pengaturan
        if (settings != null) {
            cmbBhs.setSelectedItem(settings.getLanguage()); 
        } else {
            settings = new LanguageSettings("English");
        }
    }
    private void loadSettings() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(settingsFile))) {
            settings = (LanguageSettings) ois.readObject();
        } catch (Exception e) {
            settings = new LanguageSettings("English");
        }
    }
    private void saveSettings() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(settingsFile))) {
            oos.writeObject(settings);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void updateTexts(String language) {
        if ("Indonesia".equals(language)) {
            bhs.setText("Pilih Bahasa");
            txtbhs.setText("Halo, saya Farkhan dari Kelas 4C");
            btnbhs.setText("Pilih");
            stgbhs.setText("Settingan Bahasa");
        } else { // Default ke English
            bhs.setText("Select Language");
            txtbhs.setText("Hello, I am Farkhan from Class 4C");
            btnbhs.setText("Select");
            stgbhs.setText("Language Settings");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbhs = new javax.swing.JButton();
        cmbBhs = new javax.swing.JComboBox<>();
        bhs = new javax.swing.JLabel();
        txtbhs = new javax.swing.JTextField();
        stgbhs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnbhs.setText("Pilih");
        btnbhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbhsActionPerformed(evt);
            }
        });

        cmbBhs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBhsActionPerformed(evt);
            }
        });

        bhs.setText("Pilih Bahasa");

        txtbhs.setText("Halo, saya Farkhan dari Kelas 4C");
        txtbhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbhsActionPerformed(evt);
            }
        });

        stgbhs.setText("Settingan Bahasa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbhs)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bhs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbBhs, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnbhs))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(stgbhs)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(stgbhs)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbhs)
                    .addComponent(cmbBhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtbhs, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBhsActionPerformed
      
    }//GEN-LAST:event_cmbBhsActionPerformed

    private void btnbhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbhsActionPerformed
        String selectedLanguage = (String) cmbBhs.getSelectedItem();
        settings.setLanguage(selectedLanguage);
        saveSettings();

        updateTexts(selectedLanguage);
    }//GEN-LAST:event_btnbhsActionPerformed

    private void txtbhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbhsActionPerformed

    }//GEN-LAST:event_txtbhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bhs;
    private javax.swing.JButton btnbhs;
    private javax.swing.JComboBox<String> cmbBhs;
    private javax.swing.JLabel stgbhs;
    private javax.swing.JTextField txtbhs;
    // End of variables declaration//GEN-END:variables
}
